### DISCUSSION TITLE
Using markdown to document the nodes while adhering to node-red style guide

### DISCUSSION THREAD

**Discussion by Steve-Mcl** [node-red/designs#60] [Design Proposals]
## Request
As raised by **mannharleen** in the [forum](https://discourse.nodered.org/t/using-markdown-directly-to-document-the-nodes/49592)...
> I find using the help style guide (Node help style guide : Node-RED 5) cumbersome. It takes time to document about the node using html tags.

## Additional info
Node documentation already supports markdown documentation via a script tag with `type` attribute set to `"text/markdown"`...
```html
<script type="text/markdown" data-help-name="my-node">
  Short description of my-node
  ### Inputs
  payload  (string)  the text to convert
</script>
```
...however, there is currently no means of styling the markdown to node-red documentation style guildlines.

## Proposed Solution
* Add a custom `marked` extensions to convert markup from markdown text to generate HTML that adheres to the [Node help style guide](https://nodered.org/docs/creating-nodes/help-style-guide)
* The markup should be kept simple to leave un-rendered markdown human readable

## Proposed markup

```
<script type="text/markdown" data-help-name="my-node">
Send data via a local serial port.  
### Inputs
:   payload     (string | buffer) :  data to be sent via the serial port  
:  *baudrate*   (string)          :  baudrate of the serial port (optional)  

### Outputs

1. Standard output  
:   payload   (string | buffer) :  the standard output of the command.  
:   rc        (object)          :  exec mode only, a copy of the return code object (also available on port 3)  

2. Standard Error  
:   payload   (string)          :  the standard error of the command.  
:   rc        (object)          :  exec mode only, a copy of the return code object (also available on port 3)  
</script>
```

### Result before custom extensions...
![image](https://user-images.githubusercontent.com/44235289/130327199-5e1e6bcd-ac88-4bcd-ab88-b39f2165533a.png)

### Result after custom extensions...

![image](https://user-images.githubusercontent.com/44235289/130327801-e5f2850e-f25b-4936-80d5-a428073c870b.png)

## Issues / Hurdles
* `marked` adds a `<p>` to ordered lists. This causes the text after a number in the numbered list to be on a new line.  To fix this, a new style rule is required...
```css
.red-ui-help ol.node-ports p {
    display: inline;
}
```
* There is no obvious way to enable/disable extensions. A workaround is to use a boolean flag `enableExtensions` in the custom extensions callbacks and return tokens/renderings based on its state.

## Working demo
http://jsfiddle.net/4uwfeb6n/6/

## Additional 
Tables are currently rendered with very little style making them hard to read. This proposal would also like to include CSS for node-help tables...

Markdown (standard table syntax)...
```markdown
|msg property | description                                                 |
|------------:|:------------------------------------------------------------|
| stopbits    | set `msg.stopbits` to change stop bits                      |
| parity      | set `msg.parity` to change parity                           |
| options     | a JSON object containing extra options (see example below)  |
```

Current rendering of table in node-red help side-bar...
![image](https://user-images.githubusercontent.com/44235289/130326596-229ca939-0a91-48f3-a025-4c2a63cea3d8.png)

With proposed CSS...
![image](https://user-images.githubusercontent.com/44235289/130326653-0994d0ac-dd02-43f2-9502-609a477906e6.png)

```css
.red-ui-help table {
  border-collapse: collapse;
  margin: 8px 0 8px 0;
  min-width: 300px;
  box-shadow: 0 0 2px rgb(0 0 0 / 15%);
  overflow: hidden;
  border-radius: 4px;
}

.red-ui-help table thead tr {
  background-color: #555;
  color: #ffffff;
  text-align: left;
}

.red-ui-help table th,
.red-ui-help table td {
  padding: 6px 8px;
}

.red-ui-help table tbody tr {
  border-bottom: 1px solid #dddddd;
}

.red-ui-help table tbody tr:nth-of-type(even) {
  background-color: #f3f3f3;
}

.red-ui-help table tbody tr:last-of-type {
  border-bottom: 2px solid #555;
}
```
